### ISSUE TITLE
Put PSLastPass on the PowerShell Gallery

### ISSUE THREAD

**Issue by TylerLeonhardt** [ScottEvtuch/PSLastPass#4]
Can you release PSLastPass on the [PowerShell Gallery](https://PowerShellGallery.com) so folks can install the module using `Install-Module` instead of grabbing it from GitHub?

**Comment by Tyrell66** [comment]
+1

**Comment by ScottEvtuch** [comment]
https://www.powershellgallery.com/packages/PSLastPass/1.1
