### ISSUE TITLE
Bitdefender reported issue while trying to install from PSGallery...

### ISSUE THREAD

**Issue by mvanders** [ScottEvtuch/PSLastPass#5]
Bitdefender reported issue while trying to install from PSGallery...
Infected file detected
2 minutes ago

Feature:
Antivirus

The file C:\Users\MV\AppData\Local\Temp\2bsiqfoi\Private\ConvertFrom-LPEncryptedString.ps1 is infected with Heur.BZC.PZQ.Boxter.81.923C7232 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean

**Comment by ScottEvtuch** [comment]
Unfortunately this is not something I believe I can fix on my end. You may wish to open a support ticket with Bitdefender and let them know about the false heuristic match.
