### ISSUE TITLE
-URL parameter only works if partial url is used.

### ISSUE THREAD

**Issue by i255d** [ScottEvtuch/PSLastPass#6]
I created a new password entry in LastPass, https://improving.com, I try to use it: Get-LPCredential -URL https://improving.com and it said it could not find an entry.  I tried it without the .com and it worked.  But the next day it worked with the entire URL.  Are there different databases that it checks?

**Comment by i255d** [comment]
It seems that it takes a day or so for new passwords to be accessible via the Get-LPCredential -URL command.  Does the command access a local database, or does it access the cloud.

**Comment by ScottEvtuch** [comment]
The new version 1.2 now adds a few more helpful commands/parameters to control when data is synced from LastPass. You can force a fresh sync with -Refresh or run Sync-LPData at any time.
